### ISSUE TITLE
XGBoost doesn't have proper GPU support

### ISSUE THREAD

**Issue by toph-allen** [ecohealthalliance/reservoir#16]
It looks like the GPU support in XGBoost isn't working properly (see https://github.com/ecohealthalliance/reservoir/issues/15).

It wasn't working for me in the context of calling XGBoost via caret, and I got the same error message when I ran [this demo script from the XGBoost package](https://github.com/dmlc/xgboost/blob/master/R-package/demo/gpu_accelerated.R).

```
Error in xgb.iter.update(bst$handle, dtrain, iteration - 1, obj) : 
  [22:08:21] amalgamation/../src/learner.cc:180: XGBoost version not compiled with GPU support.

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/R/site-library/xgboost/libs/xgboost.so(dmlc::StackTrace[abi:cxx11](unsigned long)+0x1fd) [0x7fc31ef41acd]
[bt] (1) /usr/local/lib/R/site-library/xgboost/libs/xgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x2d) [0x7fc31ef42a1d]
[bt] (2) /usr/local/lib/R/site-library/xgboost/libs/xgboost.so(xgboost::LearnerImpl::AssertGPUSupport()+0x4f) [0x7fc31ef70f4f]
[bt] (3) /usr/local/lib/R/site-library/xgboost/libs/xgboost.so(xgboost::LearnerImpl::ConfigureUpdaters()+0x2d5) [0x7fc31efb91c5]
[bt] (4) /usr/local/lib/R/site-library/xgboost/libs/xgboost.so(xgboost::LearnerImpl::Configure(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char
```

(I confirmed, and you can see from the paths in the error message, that I'm using the system XGBoost package, and not one I accidentally installed.)

I don't know enough about the setup to fix this myself right now, but for reference, here are the XGBoost documentation sections on [Building with GPU support](https://xgboost.readthedocs.io/en/latest/build.html#building-with-gpu-support) and [Installing R package with GPU support](https://xgboost.readthedocs.io/en/latest/build.html#installing-r-package-with-gpu-support).

**Comment by cboettig** [comment]
@noamross Sorry to jump in here... looks like this may be a problem from the multistage builds not copying everything we need.  I see: 

```
 NCCL failure :unhandled system error /xgboost/src/tree/../common/device_helpers.cuh(846)
```

on this script on the `rocker/ml-gpu` image, which looks like a path from the `xgboost` installation that wasn't copied over....

**Comment by noamross** [comment]
This is probably _not_ the same problem, as *reservoir* doesn't currently use multi-stage builds at all, but they will probably have the same solution, as ultimately it will.  I think our build might currently have xgboost for GPU installed in the `root` user library rather than the system library, which has xgboost for CPU installed in a further upstream image.

The `rocker/ml-gpu` image issue is odd, as I tested it on our GPU machine and the script worked fine.  So it's possible it relates to hardware differences? My last PR included the multi-GPU support flag, perhaps that doesn't work if you don't have multiple GPUs.

**Comment by cboettig** [comment]
@nathanathan okay, sorry for the noise, my error was caused by a missing `runtime=nvidia`.  This test file @toph-allen links actually seems to run fine on the rocker images for me...
