### ISSUE TITLE
Graphs directed by default?

### ISSUE THREAD

**Issue by scottishaccent** [ecohealthalliance/reservoir#19]
For me, at least, k_shortest_paths appears to assume that graphs are directed by default. Thus, for a very simple graph:

start   end
1       2
2       3

The following works as expected:
`k_shortest_paths(graph, from = 1, to = 3, k = 1)`
`[1] 1 2 3`

However, the reverse returns a null set:
`k_shortest_paths(graph, from = 3, to = 1, k = 1)`
`list()`

I did not see a note regarding directed vs. undirected graphs in the documentation. Is this the expected behavior of k_shortest_paths?

**Comment by noamross** [comment]
Agh, sorry, I just realized I may have sent you to the wrong repo, @scottishaccent.  This should have been filed at https://github.com/ecohealthalliance/yenpathy

**Comment by scottishaccent** [comment]
No problem, @noamross. I'll post it there shortly.
